### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by maiconkf** [andrechavesg/babi-api-horoscopo#1]
Não é possível fazer ajax através de outro domínio. Tem que liberar o acesso de sites externos para fazer a requisição.

`$.ajax({
type: 'get',
url: 'http://babi.hefesto.io/signo/escorpiao/dia',
success: function(response) {
console.log(response)
}, error: function(err) {
console.log('err')
}
})`

`Access to XMLHttpRequest at 'http://babi.hefesto.io/signo/escorpiao/dia' from origin 'http://farodi.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by andrechavesg** [comment]
Pra resolver esse problema precisa instalar o bundle de [cors](https://github.com/nelmio/NelmioCorsBundle) do symfony na aplicação. Realmente esqueci de instalar quando deployei.

Assim que eu tiver um tempo vou instalar mas se você quiser fazer o pull request ajudaria bastante =)

**Comment by greg-mattos** [comment]
+1

**Comment by ronaldomussa** [comment]
Putz Andre. Seu eu soubesse, faria esse pull. Quebrando cabeça pra encontrar uma api pra isso..

**Comment by andrechavesg** [comment]
Aproveitei que estava fazendo a instalação de CORS em uma API de um cliente e fiz aqui também =)

Liberei requisições de qualquer origem no arquivo de configuração de cors:

https://github.com/andrechavesg/babi-api-horoscopo/commit/a65990a9e07b33848aae1796b30091ac876b0b7b#diff-1239955d9c5dde13b894ad5ca3ba09a0

O valor fica isolado no arquivo .env

Fiz deploy disso também no domínio babi.hefesto.io

Vou fechar a issue agora

Valeu galera!
